sudo: false
language: node_js
node_js:
- '6'
- '4'
- '10'
cache:
  directories:
  - node_modules
branches:
  only:
    - master
    - /^greenkeeper-.*$/
notifications:
  email:
    on_success: never
env:
  global:
    - BUILD_TIMEOUT=10000
install: npm install
script: npm test
